### ISSUE TITLE
Cómo doctor puedo agendar citas para apartar el espacio en el calendario personal 

### ISSUE THREAD

**Issue by oelizondo** [ProyectoIntegrador2018/EEMI_IOS#14]
#### DESCRIPCION
* Cómo doctor puedo agendar citas para apartar el espacio en el calendario personal 
----

#### CRITERIOS DE ACEPTACION
* Se puede agendar una cita con el paciente seleccionado.

---
#### DETALLES IMPORTANTES NO-FUNCIONALES
-------

#### PRIORIDAD
* Alta
----

#### TO-DO

- [x] Code review
- [x] Diseñar vistas
- [x] Programar vistas
- [x] Asignar una fecha para la consulta
- [x] Asociar consulta con el paciente
- [x] Salvar la cita
- [x] Mensajes de error
- [x] Merge
