### ISSUE TITLE
Mensajes de Error

### ISSUE THREAD

**Issue by Jelizondo** [ProyectoIntegrador2018/EEMI_IOS#23]
#### DESCRIPCION
* Agregar mensajes de error mas descriptivos
----

#### CRITERIOS DE ACEPTACION
* Todos los errores tienen una descripción apropiada dependiendo del tipo de error.
* Todos los errores tienen que estar en español.
---

#### PRIORIDAD
* Alta
----

#### TO-DO

- [x] Code review
- [x] Descripción de error: Conexión a internet (Agenda, Login, Pacientes, Exepediente)
- [x] Descripción de error: De Sesión 
- [x] Descripción de error: Errores agendando citas
- [x] Descripción de error: Iniciar Sesión y autorización local
- [x] Descripción de error: Lista de pacientes (genérico)
- [x] Descripción de error: Expediente de pacientes (genérico)
- [x] Descripción de error: Agenda (generico)
