### ISSUE TITLE
[WIP] Manejo de información vacía

### ISSUE THREAD

**Issue by Jelizondo** [ProyectoIntegrador2018/EEMI_IOS#24]
#### DESCRIPCION
* Agregar manejo de información vacía para el detalle de expediente y en la lista de pacientes
----

#### CRITERIOS DE ACEPTACION
* Todos los campos de información tienen que tener un placeholder en caso de no tener información.
* Todos los placeholders tienen que estar en español.
---

#### PRIORIDAD
* Baja
----

#### TO-DO

- [x] Code review
- [x] Cuando no hay pacientes registrados para el doctor desplegar el placeholder apropiado.
- [x] Cuando solamente hay un familiar solo desplegar el campo para ese familiar.
- [x] Cuando no hay inmunizaciones o consultas desplegar el placeholder apropiado.

**Comment by Jelizondo** [comment]
#### DESCRIPCION
* Agregar manejo de información vacía para el detalle de expediente y en la lista de pacientes
----

#### CRITERIOS DE ACEPTACION
* Todos los campos de información tienen que tener un placeholder en caso de no tener información.
* Todos los placeholders tienen que estar en español.
---

#### PRIORIDAD
* Alta
----

#### TO-DO

- [ ] Code review
- [ ] Cuando no tiene familiares: desplegar "No hay familiares registrados".
- [ ] Cuando solamente hay un familiar solo desplegar el campo para ese familiar.
- [ ] Cuando no hay inmunizaciones o consultas desplegar el placeholder apropiado.
